// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDsTHzdVwE8z6nNag1GPSvemUJikhATdg',
    appId: '1:191686723958:web:08ae5ce4a8615633481257',
    messagingSenderId: '191686723958',
    projectId: 'trinetra-24318',
    authDomain: 'trinetra-24318.firebaseapp.com',
    storageBucket: 'trinetra-24318.firebasestorage.app',
    measurementId: 'G-EFNYD9VRFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMvQ6XzcgapgTD_C3xAkpDygNHyhcxhjg',
    appId: '1:37224293536:android:7372dd9159c4b2720815c5',
    messagingSenderId: '37224293536',
    projectId: 'trinetra-24318',
    databaseURL: 'https://trinetra-24318-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trinetra-24318.firebasestorage.app',

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNNO7TFSaqeduBzeSD2vbdX0R-DzcH258',
    appId: '1:191686723958:ios:cda108226c80685b481257',
    messagingSenderId: '191686723958',
    projectId: 'trinetra-24318',
    storageBucket: 'trinetra-24318.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  );

  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDsTHzdVwE8z6nNag1GPSvemUJikhATdg',
    appId: '1:191686723958:web:613ac278dade45a9481257',
    messagingSenderId: '191686723958',
    projectId: 'trinetra-24318',
    authDomain: 'trinetra-24318.firebaseapp.com',
    storageBucket: 'trinetra-24318.firebasestorage.app',
    measurementId: 'G-77WNYVCGCV',
  );

}