// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFnJw-8n9K_7D9AWVMWVi_I9JrTYGe5x0',
    appId: '1:37224293536:web:e02edf584d6cad720815c5',
    messagingSenderId: '37224293536',
    projectId: 'trinetra-c7c20',
    authDomain: 'trinetra-c7c20.firebaseapp.com',
    databaseURL: 'https://trinetra-c7c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trinetra-c7c20.firebasestorage.app',
    measurementId: 'G-JYTTGM8DPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMvQ6XzcgapgTD_C3xAkpDygNHyhcxhjg',
    appId: '1:37224293536:android:7372dd9159c4b2720815c5',
    messagingSenderId: '37224293536',
    projectId: 'trinetra-c7c20',
    databaseURL: 'https://trinetra-c7c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trinetra-c7c20.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUYRS1dhzpzbCTwnz92mD0DMDptPlPXps',
    appId: '1:37224293536:ios:2a5be094acc22ac00815c5',
    messagingSenderId: '37224293536',
    projectId: 'trinetra-c7c20',
    databaseURL: 'https://trinetra-c7c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trinetra-c7c20.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUYRS1dhzpzbCTwnz92mD0DMDptPlPXps',
    appId: '1:37224293536:ios:2a5be094acc22ac00815c5',
    messagingSenderId: '37224293536',
    projectId: 'trinetra-c7c20',
    databaseURL: 'https://trinetra-c7c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trinetra-c7c20.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFnJw-8n9K_7D9AWVMWVi_I9JrTYGe5x0',
    appId: '1:37224293536:web:aaea819283cb57510815c5',
    messagingSenderId: '37224293536',
    projectId: 'trinetra-c7c20',
    authDomain: 'trinetra-c7c20.firebaseapp.com',
    databaseURL: 'https://trinetra-c7c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trinetra-c7c20.firebasestorage.app',
    measurementId: 'G-JB4ZNSX0QH',
  );
}
